Fs = 87099.71 # Частота дискритизация
KEY_TIME_STAMP = 'TIME_STAMP'
KEY_FREQ = 'FREQ'
KEY_DATA = 'DATA'
KEY_EXPERIMENT_NAME = 'EXPERIMENT_NAME'
KEY_EXPERIMENT_DATE = 'EXPERIMENT_DATE'
KEY_PARSED_DATA = 'PARSED_DATA'
