Fs = 87099.71 # Частота дискритизация
ADC_SCALE = 4096 # разрядность АЦП
KEY_TIME_STAMP = 'TIME_STAMP'

KEY_CHANNEL0 = 'Ch0'
KEY_CHANNEL1 = 'Ch1'

KEY_FREQ = 'FREQ'
KEY_DATA = 'DATA'
KEY_EXPERIMENT_NAME = 'EXPERIMENT_NAME'
KEY_EXPERIMENT_DATE = 'EXPERIMENT_DATE'
KEY_PARSED_DATA     = 'PARSED_DATA'

KEY_SIGNAL_FFT         = 'SIGNAL_FFT'
KEY_SIGNAL_X_AX        = 'SIGNAL_X_AX'
KEY_SIGNAL_OFFSET      = 'SIGNAL_OFFSET'
KEY_SIGNAL_COMPLEX_VAL = 'SIGNAL_COMPLEX_VAL'
KEY_SIGNAL_ABS_VAL     = 'SIGNAL_ABS_VAL'